# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"0\n\nOcrRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x11\n\tfile_type\x18\x02 \x01(\t\"~\n\x0bOcrResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x30\n\x08metadata\x18\x02 \x03(\x0b\x32\x1e.ocr.OcrResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x42\n\nOcrService\x12\x34\n\x0fProcessDocument\x12\x0f.ocr.OcrRequest\x1a\x10.ocr.OcrResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OCRRESPONSE_METADATAENTRY']._options = None
  _globals['_OCRRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_OCRREQUEST']._serialized_start=18
  _globals['_OCRREQUEST']._serialized_end=66
  _globals['_OCRRESPONSE']._serialized_start=68
  _globals['_OCRRESPONSE']._serialized_end=194
  _globals['_OCRRESPONSE_METADATAENTRY']._serialized_start=147
  _globals['_OCRRESPONSE_METADATAENTRY']._serialized_end=194
  _globals['_OCRSERVICE']._serialized_start=196
  _globals['_OCRSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
